
from __future__ import annotations

from typing import Any

from ai.interfaces import FormattedResponse
from logger import logger


class ResponseFormatter:

    def format(
        self,
        *,
        message: str,
        data: list[dict[str, Any]],
        sql: str,
        strategy: str,
        confidence: float,
        used_uploads: bool = False,
    ) -> FormattedResponse:
        try:
            conf = float(confidence) if confidence is not None else 0.0
            explanation = self._generate_explanation(
                strategy, sql=sql, used_uploads=used_uploads
            )

            metadata: dict[str, Any] = {
                "sql": sql,
                "strategy": strategy,
                "confidence": conf,
                "confidence_label": self._get_confidence_label(conf),
                "explanation": explanation,
                "row_count": len(data),
                "data_preview": data[:5] if data else [],
                "used_uploads": used_uploads,
            }

            return FormattedResponse(
                message=message,
                data=data,
                metadata=metadata,
            )

        except Exception as e:
            logger.warning("formatter: %s", e)
            return FormattedResponse(
                message=f"Error formatting response: {e}",
                data=[],
                metadata={"error": str(e)},
            )

    @staticmethod
    def _generate_explanation(
        strategy: str, *, sql: str, used_uploads: bool
    ) -> str:
        if strategy == "template":
            return (
                "This response used a pre-validated query template designed for "
                "common questions about orders and support tickets."
            )
        if strategy == "plan_built":
            return (
                "This response used a deterministic query plan: tables, joins, "
                "and filters were chosen by the server from a bounded intent, "
                "not invented freely by a language model."
            )
        if used_uploads:
            return (
                "This response used a custom SQL query that may include your "
                "uploaded spreadsheet rows (uploads.dataset_rows), joined to "
                "ecommerce or support tables when relevant."
            )
        return (
            "This response was generated by analyzing your natural language "
            "question and creating a custom SQL query across customer, order, "
            "and support ticket records."
        )

    @staticmethod
    def _get_confidence_label(confidence: float) -> str:
        if confidence >= 0.9:
            return "high"
        if confidence >= 0.6:
            return "medium"
        return "low"
